language: node_js
node_js:
- '0.12'
before_script:
- npm link
deploy:
  provider: npm
  email: rodrigo.mangue@gmail.com
  api_key:
    secure: Se7wZsJO9p9/tzr9cQsxskicjgS/8b4a625oM4BA/+rcf3SV8zOoLPeGqYx4L/cItqzK783NoRsu2icmFHzYll3VEWxEIERGoPGyB8LB80mLhX4eKhUZ5xGD2Y2LrJxkHUpAhU+npbjxcfTFsLzrp/hpckhzHyNPJzuwGxVj6zQ=
  on:
    tags: true
    repo: rodrigo-medeiros/coderbits
